# Generated by Django 2.0.6 on 2020-12-10 14:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adhaar_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid Adhaar number entered', regex='^[123456789][0-9]{9}$')]),
            preserve_default=False,
        ),
    ]
