# Generated by Django 2.0.6 on 2020-12-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_adhaar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adhaar_number',
        ),
    ]
